name: task_app
description: "A professional Task Management application built for  technical assignment."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5+1

  # API & Networking
  dio: ^5.9.1

  # Security (Token Storage)
  flutter_secure_storage: ^10.0.0

  # Date Formatting
  intl: ^0.20.2

  # UX/UI Enhancement (Loading Effect)
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
